Rails3/agendafarmacoequip/config/routes.rb
Calendar::Application.routes.draw do
  resources :tipo_usuarios

  devise_for :admins
  devise_for :usuarios

  resources :events
  resources :agendamentos
  resources :tipos

  match 'agendamento' => 'agendamento#index'
  match 'erro_criacao' => 'event#erro'
  match 'to_evento' => 'events#show_one'
  match 'escolha' => 'acessos#index'
  match 'sala_equipamento' => 'calendar#unico'
  match 'admin_novo_evento' => 'admin#new'
  match 'admin_evento_show' => 'admin#show'
  match 'login_devise' => 'login#calendario'
  match 'admin_eventos' => 'tipos#eventos'
  match 'admin_rejeita' => 'admin_event#rejeita'
  match 'admin_aceita' => 'admin_event#aceita'
  match 'ver_usuario' => 'admin#ver_usuarios'
  match 'permissoes' => 'admin#permissoes'
  match 'permitir' => 'tipo_usuarios#edit'
  match 'tirapermissao' => 'tipo_usuarios#destroy'
  match 'ver_dia' => 'events#ver_dia'
  match 'monta_relatorio' => 'events#monta_relatorio'
  match 'newindex' => 'events#newindex'
  match 'newindex_admin' => 'admin#newindex'
  match 'index_event' => 'events#index_event'
  match 'index_event_admin' => 'admin#index_event'
  match 'pre_form' => 'events#pre_form'
  get 'show_ags/:id' => 'events#show_ags', as: 'show_ags'
  get 'show_ags_admin/:id' => 'admin#show_ags', as: 'show_ags_admin'

  get 'tipodescricao/:tipo_id' => 'events#tipodescricao', :as => 'tipodescricao'

  get "calendar/index"

  root :to => "events#redireciona"

end

Rails3/agendafarmacoequip/app/models/tipo.rb
class Tipo < ActiveRecord::Base

  has_many :tipo_usuarios, dependent: :destroy
  has_many :events
  has_and_belongs_to_many :tipo_usuarios
  validates_presence_of :nome

  after_create :inserir_permissoes_para_novo_tipo

  private
	  def inserir_permissoes_para_novo_tipo
	  	usuarios=Usuario.all
	  	usuarios.each do |usr|
	  		TipoUsuario.create(usuario_id: usr.id, tipo_id: self.id)
	  	end
	  end

end

Rails3/agendafarmacoequip/app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  # GET /tipos
  # GET /tipos.xml
  before_filter :authenticate_admin!

  #Cadastro do tipo do agendamento
  def index
    @tipos = Tipo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tipos }
    end
  end

  # GET /tipos/1
  # GET /tipos/1.xml
  def show
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tipo }
    end
  end

  # GET /tipos/new
  # GET /tipos/new.xml
  def new
    @tipo = Tipo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tipo }
    end
  end

  # GET /tipos/1/edit
  def edit
    @tipo = Tipo.find(params[:id])
  end

  # POST /tipos
  # POST /tipos.xml
  def create
    @tipo = Tipo.new(params[:tipo])

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to(@tipo, :notice => "Sala ou equipamento criado com sucasso.") }
        format.xml  { render :xml => @tipo, :status => :created, :location => @tipo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tipo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipos/1
  # PUT /tipos/1.xml
  def update
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      if @tipo.update_attributes(params[:tipo])
        format.html { redirect_to(@tipo, :notice => 'Sala ou equipamento alterado com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tipo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.xml
  def destroy
    @tipo = Tipo.find(params[:id])
    @tipo.destroy

    respond_to do |format|
      format.html { redirect_to(tipos_url) }
      format.xml  { head :ok }
    end
  end


  def eventos
    @u = current_admin
    @tipo = Tipo.find(params[:id])

    #somente o admin da sala ve os eventos da sala
    if @u.email == @tipo.email
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @tipo }
      end
    else
      respond_to do |format|
        format.html { redirect_to :controller => 'calendar', :action => 'index' }
      end
    end
  end


  


end

Rails3/agendafarmacoequip/app/helpers/tipos_helper.rb
module TiposHelper
end

Rails3/agendafarmacoequip/app/views/tipos/_form.html.erb
<%= form_for(@tipo) do |f| %>
    <% if @tipo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tipo.errors.count, "error") %> Falha ao salvar:</h2>

          <ul>
            <% @tipo.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :nome,"Nome" %><br />
      <%= f.text_field :nome %>
    </div>
    <div class="field">
      <%= f.label :cor,"Cor" %><br />
      <%= f.text_field :cor %>
    </div>
    <div class="field">
      <%= f.label :email,"E-mail do administrador" %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :observacao, "Observação" %><br />
      <%= f.text_area :observacao %>
    </div>
    <div>
      <%= f.check_box :confirmacao %>
      <%= f.label :confirmacao, "Equipamento necessita confirmação." %>
    </div>

    <div class="actions">
      <%= f.submit "Enviar" %>
    </div>
<% end %>

<script>
$(document).ready(function(){
  $("#tipo_cor").spectrum({
    preferredFormat: "hex",
    chooseText: "Escolha a cor",
    cancelText: "Cancelar"
  });
});
</script>

Rails3/agendafarmacoequip/app/views/tipos/_tipo_usuario.html.erb
<p>
  <% for tipo_usuario in Tipo_usuario.all(:order => "id ASC") %>
      <%= check_box_tag "usuario[tipo_usuario_id][]", tipo_usuario.id, tipo_usuario_ids.include?(tipo_usuario.id) %>
      <%= tipo_usuario.tipo_id %>
  <% end %>
</p>

Rails3/agendafarmacoequip/app/views/tipos/edit.html.erb
<h1>Editar Equipamentos</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @tipo %> |
<%= link_to 'Voltar', tipos_path %>

Rails3/agendafarmacoequip/app/views/tipos/eventos.html.erb
<h2 align="center">Estes são os agendamentos marcados para essa sala ou equipamento selecionado:</h2>



<!-- cria uma tabela para listar os eventos -->
<table id="tabela_index" cellpadding="3" cellspacing="3" align="center">
  <tr>
    <th class="t1">Titulo</th>
    <th class="t1">Início</th>
    <th class="t1">Fim</th>
    <th class="t1">Descrição</th>
    <th class="t1"></th>
    <th class="t1"></th>
    <th class="t1"></th>
  </tr>

  <!-- acha todos os eventos e compara para ver se o tipo é compatível -->
  <% @event = Event.find(:all) %>
  <% @event.each do |e| %>
      <% if e.tipo_id == @tipo.id %>

          <!-- completa a tabela com os dados dos eventos existentes que são compatíveis com o tipo -->
          <tr>
            <td class="t1"><%= e.title %></td>
            <td class="t1"><%= e.starts_at.to_datetime.strftime("%d/%m/%Y %H:%M") %></td>
            <td class="t1"><%= e.ends_at.to_datetime.strftime("%d/%m/%Y %H:%M") %></td>
            <td class="t1"><%= e.description %></td>
            <td class="t1"><%= link_to 'Mostrar', :controller => 'admin', :action => 'show', :id => e.id %></td>
            <% if e.pendente == true %>
                <td class="t1" align="center"><%= link_to 'Aceitar', :controller => 'admin_event', :action => 'aceita', :id => e.id %></td>
                <td class="t1"><%= link_to 'Recusar', :controller => 'admin_event', :action => 'rejeita', :id => e.id %></td>
            <% else %>
                <td class="t1">Confirmado</td>
            <% end %>
          </tr>
      <% end %>
  <% end %>
</table>


<p align="center"> <%= link_to "Voltar", tipos_path %>  </p>

Rails3/agendafarmacoequip/app/views/tipos/index.html.erb
<h1>Listando Equipamentos</h1>

<div class="container">

<table class="table table-bordered display">
  <tr>
    <th class="text-center">Nome</th>
    <th class="text-center">Observação</th>
    <th class="text-center"></th>
    <th class="text-center" colspan="2"></th>
  <tr>

<% @tipos.each do |tipo| %>
  <tr>
    <td><%= tipo.nome %></td>
    <td><%= tipo.observacao %></td>
    <td class="text-center"><%= link_to 'Mostrar', tipo %></td>
    <td class="text-center"><%= link_to 'Editar', edit_tipo_path(tipo) %></td>
    <!-- <td>< %= link_to 'Mostrar eventos', :controller => 'tipos', :action => 'eventos', :id => tipo.id %></td> -->
  </tr>
<% end %>
</table>

</div>

<p align="center"><%= link_to 'Novo Equipamento',:controller => 'tipos', :action => 'new' %>  |
<%= link_to "Voltar", calendar_index_path %> </p>

Rails3/agendafarmacoequip/app/views/tipos/new.html.erb
<h1>Novo Equipamento</h1>

<%= render 'form' %>

<%= link_to 'Voltar', tipos_path %>

Rails3/agendafarmacoequip/app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @tipo.nome %>
</p>

<p>
  <b>Observação:</b>
  <%= @tipo.observacao %>
</p>


<%= link_to 'Editar', edit_tipo_path(@tipo) %> |
<%= link_to 'Voltar', tipos_path %>