Rails4/galeria_ICB/config/routes.rb
Rails.application.routes.draw do

  get 'welcome/login'
  get 'welcome/callback'

  get 'logout' => 'welcome#destroy', as: 'logout'

  get 'escolhe_capa/:id' => 'albuns#escolher_capa', as: 'escolhe_capa'
  get 'definir_capa/:id' => 'albuns#definir_capa', as: 'definir_capa'
  get 'mostrar/:id' => 'colecao#mostrar', as: 'mostrar'
  get 'busca_tag' => 'colecao#busca_tag', as: 'busca_tag'
  get 'resultado_busca_tag' => 'colecao#resultado_busca_tag', as: 'resultado_busca_tag'
  get 'pesquisa' => 'colecao#pesquisa', as: 'pesquisa'
  get 'repete_legenda' => 'albuns#repete_legenda', as: 'repete_legenda'

  resources :albuns
  resources :fotos
  resources :departamentos
  resources :categorias
  resources :colecao
  resources :tags
  resources :permitidos
  resources :perfils
  resources :logs
  resources :usuarios

  root 'colecao#index'

end

Rails4/galeria_ICB/app/models/album.rb
class Album < ActiveRecord::Base

  #before_destroy :remove_file_zip


  belongs_to :categoria
  belongs_to :departamento
  has_many :tags, dependent: :destroy
  has_many :fotos, dependent: :destroy



  accepts_nested_attributes_for :tags, :allow_destroy => true
  #accepts_nested_attributes_for :fotos, :allow_destroy => true, reject_if: proc { |a| a['arquivo'].blank? }
  accepts_nested_attributes_for :fotos, :allow_destroy => true


  validates_presence_of :data_evento
  validates_presence_of :nome_evento_assunto
  validates_presence_of :nome_fotografo




end

Rails4/galeria_ICB/app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :albums
  has_many :fotos

  validates_presence_of :nome
end

Rails4/galeria_ICB/app/models/departamento.rb
class Departamento < ActiveRecord::Base
  has_many :albuns
end

Rails4/galeria_ICB/app/models/foto.rb
class Foto < ActiveRecord::Base

  after_destroy :remove_file_directory




  mount_uploader :arquivo, ArquivoUploader
  belongs_to :album

  validates :arquivo, file_size: { less_than: 5.megabytes}

  def remove_file_directory
    path = File.expand_path(arquivo.store_path, arquivo.root)
    FileUtils.remove_dir(path, force: false)
  end



end

Rails4/galeria_ICB/app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :usuario

end

Rails4/galeria_ICB/app/models/perfil.rb
class Perfil < ActiveRecord::Base

  has_many :permitidos
  has_many :usuarios, through: :permitidos

end

Rails4/galeria_ICB/app/models/permitido.rb
class Permitido < ActiveRecord::Base

  belongs_to :usuario
  belongs_to :perfil

end

Rails4/galeria_ICB/app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :album
end

Rails4/galeria_ICB/app/models/tipo_vinculo.rb
class TipoVinculo < ActiveRecord::Base
    belongs_to :usuario
end

Rails4/galeria_ICB/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :tipo_vinculos
  has_many :logs

  has_many :permitidos, dependent: :destroy
  has_many :perfils, through: :permitidos
end

Rails4/galeria_ICB/app/controllers/logs_controller.rb
class LogsController < ApplicationController

  before_action :set_log, only: [:show]
  before_filter 'autenticado?'


  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all.order('id desc')
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:acao, :ip)
    end
end

Rails4/galeria_ICB/app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController

  before_action :set_perfil, only: [:show, :edit, :update]
  before_filter 'autenticado?'          

  # GET /perfils
  # GET /perfils.json
  def index
    @perfils = Perfil.all
  end

  # GET /perfils/1
  # GET /perfils/1.json
  def show
  end

  # GET /perfils/new
  def new
    @perfil = Perfil.new
  end

  # GET /perfils/1/edit
  def edit
  end

  # POST /perfils
  # POST /perfils.json
  def create
    @perfil = Perfil.new(perfil_params)

    respond_to do |format|
      if @perfil.save
        addlog("Criou um novo perfil")
        format.html { redirect_to @perfil, notice: 'Perfil foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @perfil }
      else
        format.html { render :new }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfils/1
  # PATCH/PUT /perfils/1.json
  def update
    respond_to do |format|
      if @perfil.update(perfil_params)
        addlog("Atualizou um perfil")
        format.html { redirect_to @perfil, notice: 'Perfil foi atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @perfil }
      else
        format.html { render :edit }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfil_params
      params.require(:perfil).permit(:tipo)
    end
end

Rails4/galeria_ICB/app/controllers/tags_controller.rb
class TagsController < ApplicationController


PER_PAGE = 400
  def index
    #@tags = Tag.all.order('album_id').page(params[:page]).per(PER_PAGE)
    @tags = Tag.select('nome').order('id desc').uniq.page(params[:page]).per(PER_PAGE)
  end
end

Rails4/galeria_ICB/app/helpers/albuns_helper.rb
module AlbunsHelper
end

Rails4/galeria_ICB/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails4/galeria_ICB/app/helpers/categorias_helper.rb
module CategoriasHelper
end

Rails4/galeria_ICB/app/helpers/colecao_helper.rb
module ColecaoHelper
end

Rails4/galeria_ICB/app/helpers/fotos_helper.rb
module FotosHelper
end

Rails4/galeria_ICB/app/helpers/legenda_helper.rb
module LegendaHelper
end

Rails4/galeria_ICB/app/helpers/logs_helper.rb
module LogsHelper

  def addlog(acao)

    @log  = Log.new

    @log.acao = acao
    @log.usuario_id = current_user.id
    @log.ip = request.remote_addr

    @log.save!

  end

end

Rails4/galeria_ICB/app/helpers/tags_helper.rb
module TagsHelper
end

Rails4/galeria_ICB/app/helpers/welcome_helper.rb
module WelcomeHelper

  #cria uma sessão
  def log_in(loginUsuario)
    session[:login] = loginUsuario
  end

  #destroi a sessão criada na def anterior
  def log_out
    session.destroy
    @current_user = nil
  end

  def current_user
    @current_user ||= Usuario.find_by(loginUsuario: session[:login])
  end

  def carregaperfils

    @perfilscadastrados = Permitido.where(:usuario_id => current_user.id)

    session[:perfil] ||= []

    @perfilscadastrados.each do |p|
      session[:perfil] << p.perfil.tipo
    end
  end




end

Rails4/galeria_ICB/app/views/perfils/_form.html.erb
<%= form_for(@perfil) do |f| %>
  <% if @perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perfil.errors.count, "error") %> prohibited this perfil from being saved:</h2>

      <ul>
      <% @perfil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo, "Tipo do perfil" %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-primary active" %>
  </div>
<% end %>

Rails4/galeria_ICB/app/views/perfils/edit.html.erb
<h1>Editar Perfil</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @perfil, class: "btn btn-primary active" %> |
<%= link_to 'Voltar', perfils_path, class: "btn btn-default" %>

Rails4/galeria_ICB/app/views/perfils/index.html.erb
<h1>Perfis</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="text-center">Tipo</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @perfils.each do |perfil| %>
      <tr>
        <td><%= perfil.tipo %></td>
        <td class="text-center"><%= link_to 'Mostrar', perfil, class: "btn btn-default" %></td>
        <td class="text-center"><%= link_to 'Editar', edit_perfil_path(perfil), class: "btn btn-primary active" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Perfil', new_perfil_path, class: "btn btn-primary active" %>

Rails4/galeria_ICB/app/views/perfils/new.html.erb
<h1>Novo Perfil</h1>

<%= render 'form' %>

<%= link_to 'Voltar', perfils_path, class: "btn btn-default"  %>

Rails4/galeria_ICB/app/views/perfils/show.html.erb
<p>
  <strong>Tipo:</strong>
  <%= @perfil.tipo %>
</p>

<%= link_to 'Editar', edit_perfil_path(@perfil), class: "btn btn-primary active" %> |
<%= link_to 'Voltar', perfils_path, class: "btn btn-default" %>