Rails3/agendafarmacoequip/config/routes.rb
Calendar::Application.routes.draw do
  resources :tipo_usuarios

  devise_for :admins
  devise_for :usuarios

  resources :events
  resources :agendamentos
  resources :tipos

  match 'agendamento' => 'agendamento#index'
  match 'erro_criacao' => 'event#erro'
  match 'to_evento' => 'events#show_one'
  match 'escolha' => 'acessos#index'
  match 'sala_equipamento' => 'calendar#unico'
  match 'admin_novo_evento' => 'admin#new'
  match 'admin_evento_show' => 'admin#show'
  match 'login_devise' => 'login#calendario'
  match 'admin_eventos' => 'tipos#eventos'
  match 'admin_rejeita' => 'admin_event#rejeita'
  match 'admin_aceita' => 'admin_event#aceita'
  match 'ver_usuario' => 'admin#ver_usuarios'
  match 'permissoes' => 'admin#permissoes'
  match 'permitir' => 'tipo_usuarios#edit'
  match 'tirapermissao' => 'tipo_usuarios#destroy'
  match 'ver_dia' => 'events#ver_dia'
  match 'monta_relatorio' => 'events#monta_relatorio'
  match 'newindex' => 'events#newindex'
  match 'newindex_admin' => 'admin#newindex'
  match 'index_event' => 'events#index_event'
  match 'index_event_admin' => 'admin#index_event'
  match 'pre_form' => 'events#pre_form'
  get 'show_ags/:id' => 'events#show_ags', as: 'show_ags'
  get 'show_ags_admin/:id' => 'admin#show_ags', as: 'show_ags_admin'

  get 'tipodescricao/:tipo_id' => 'events#tipodescricao', :as => 'tipodescricao'

  get "calendar/index"

  root :to => "events#redireciona"

end

Rails3/agendafarmacoequip/app/views/admin/index_event.html.erb
<h1 id="events">Listando  eventos</h1>

<div class="container">

<% @usuario = current_usuario %>

<table id="tabela_index" class="table table-bordered display">
  <tr>
    <th class="t1 text-center">Titulo</th>
    <th class="t1 text-center">Registrado para</th>
    <th class="t1 text-center">Início</th>
    <th class="t1 text-center">Fim</th>
    <th class="t1 text-center">Descrição</th>
    <th class="t1 text-center"></th>
    <th class="t1 text-center"></th>
    <th class="t1 text-center"></th>
  </tr>

  <% @events.each do |ea| %>
      <tr>
        <td class="t1"><%= ea.title %></td>
        <td class="t1"><%= ea.regpara  %></td>
        <td class="t1"><%= ea.starts_at.to_datetime.strftime("%d/%m/%Y %H:%M") %></td>
        <td class="t1"><%= ea.ends_at.to_datetime.strftime("%d/%m/%Y %H:%M") %></td>
        <td class="t1"><%= ea.description %></td>
        <td class="t1 text-center"><%= link_to 'Mostrar', :controller => 'events', :action => 'show_one', :id => ea.id %></td>
        <td class="t1 text-center"><%= link_to 'Excluir', ea, method: :delete, confirm: 'Tem certeza?'  %></td>
        <td class="t1 text-center"><%= link_to "Mostrar agendamentos", show_ags_admin_path(ea.id) %>  </td>
      </tr>
  <% end %>
</table>

</div>

<br/>
<div id="rodape" align="center">
  <%= link_to 'Ver calendario', calendar_index_path %>
</div>

Rails3/agendafarmacoequip/app/views/admin/newindex.html.erb
<h1 id="events">Listando  Agendamentos</h1>

<% @admin = current_admin %>

<table id="tabela_index" cellpadding="3" cellspacing="3" align="center">
  <tr>
    <th class="t1">Tipo</th>
    <th class="t1">Titulo</th>
    <th class="t1">Registrado para</th>
    <th class="t1">Registrado por</th>
    <th class="t1">Início</th>
    <th class="t1">Fim</th>
    <th class="t1">Descrição</th>
    <th class="t1"></th>
    <th class="t1"></th>
  </tr>

  <% for event in @event_tipo %>
      <tr>
        <td class="t1"><%= event.nome %></td>
        <td class="t1"><%= event.title %></td>
        <td class="t1"><%= event.regpara  %></td>
       <td class="t1"><%= event.nome_completo %></td>
        <td class="t1"><%= event.starts_at.to_datetime.strftime("%d/%m/%Y ") %> <%= event.inicio %></td>
        <td class="t1"><%= event.ends_at.to_datetime.strftime("%d/%m/%Y ") %><%= event.fim %></td>
        <td class="t1"><%= event.description %></td>
        <td class="t1"><%= link_to 'Mostrar', :controller => 'events', :action => 'show_one', :id => event.id %></td>
        <td class="t1"><%= link_to 'Editar', edit_event_path(event) %></td>
        <td class="t1"><%= link_to 'Excluir', event, method: :delete %></td>
      </tr>
  <% end %>
</table>

<br/>
<div id="rodape" align="center">
  <%= link_to 'ver calendario', calendar_index_path %> |
  <%= link_to 'Novo Evento', new_event_path %>
</div>

Rails3/agendafarmacoequip/app/views/admin/show.html.erb
<h2 align="center">Evento selecionado:</h2>

<% @agandamento = Agendamento.find(:all) %>
<% @event = Event.find(params[:id]) %>

<table id="tab_show_one" cellpadding="20" align="center">


  <tr class="par"><td>
    <b>Sala:</b>
    <% @tipo = Tipo.find(:all) %>
    <% @tipo.each do |t| %>
        <% if t.id == @event.tipo_id %>
            <%= t.nome %>
        <% end %>
    <% end %>
  </td></tr>

  <tr class="impar"><td>
    <b>Título:</b>
    <%= @event.title %>
  </td></tr>

  <tr class="par"><td>
    <b>Registrado para:</b>
    <%= @event.regpara %>
  </td></tr>

  <tr class="impar"><td>
    <b>Início em:</b>
    <%= @event.starts_at.to_datetime.strftime("%d/%m/%Y %H:%M") %>
  </td></tr>

  <tr class="par"><td>
    <b>Término em:</b>
    <%= @event.ends_at.to_datetime.strftime("%d/%m/%Y %H:%M") %>
  </td></tr>


  <tr class="impar"><td>

    <b>Dias selecionados:</b>
    <ul>
      <% if @event.domingo == true %>
          <li>Domingo</li>
      <% end %>
      <% if @event.segunda == true %>
          <li>Segunda-feira</li>
      <% end %>
      <% if @event.terca == true %>
          <li>Terça-feira</li>
      <% end %>
      <% if @event.quarta == true %>
          <li>Quarta-feira</li>
      <% end %>
      <% if @event.quinta == true %>
          <li>Quinta-feira</li>
      <% end %>
      <% if @event.sexta == true %>
          <li>Sexta-feira</li>
      <% end %>
      <% if @event.sabado == true %>
          <li>Sábado</li>
      <% end %>
    </ul>
  </td></tr>

  <tr class="par">
    <td><b>Descrição:</b>
    <%= @event.description %>
    </td></tr>
</table>

Rails3/agendafarmacoequip/app/views/admin/show_ags.html.erb
<h1 id="events">Listando  agendamentos</h1>

<div class="container">

<% @usuario = current_usuario %>


<table id="tabela_index" class="table table-bordered display">
  <tr>
    <th class="t1 text-center">Data inicio</th>
    <th class="t1 text-center">Data fim</th>
    <th class="t1 text-center">Hora Inicio</th>
    <th class="t1 text-center">Hora Fim</th>
    <th></th>
  </tr>

    <% @event.agendamentos.each do |ea| %>
    <tr>
      <td class="t1"><%= ea.data_inicio.strftime("%d/%m/%Y") %> </td>
      <td class="t1"><%= ea.data_fim.strftime("%d/%m/%Y") %> </td>
      <td class="t1"><%= ea.inicio %> </td>
      <td class="t1"><%= ea.fim %> </td>
      <td class="t1 text-center"><%= link_to 'Excluir', ea, method: :delete, confirm: "Tem certeza?",  redirect_to: calendar_index_path %></td>
    </tr>
    <% end %>
  </table>

</div>

<%= link_to "Voltar", index_event_admin_path %> </p>

Rails3/agendafarmacoequip/app/views/admin/ver_usuarios.html.erb
<h1>Lista de usuarios:</h1>
<table>

  <tr>
    <td>Login</td>
    <td>Nome</td>
    <td>Data do último acesso</td>
    <td>Hora do último acesso</td>
    <td></td>
  </tr>

  <% @usuario.each do |user| %>
      <tr>
        <td><%= user.email %></td>
    	<td><%= user.nome_completo %></td>
        <td><%= user.last_sign_in_at.to_datetime.strftime("%d/%m/%Y") %></td>
        <td><%= user.last_sign_in_at.to_datetime.strftime("%H:%M:%S") %></td>
        <td><%= link_to 'Alterar permissões', :controller => 'tipo_usuarios', :action => 'new', :id => user.id %></td>
      </tr>
  <% end %>

</table>

<p> <%= link_to "Voltar", calendar_index_path %> </p>